services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: unless-stopped
  answer-pipeline:
    image: ghcr.io/semantic-hallucinations/answer_pipeline:8f7cd9e325242e500c05f38247f367e0a591a215
    ports:
      - "8080:8000"
    env_file:
      - .env
  tele-bot:
    image: ghcr.io/semantic-hallucinations/bsuir-helper-bot:d3eebd5b45edf42f6f13497e32742ce2fef050a1
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
